apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  labels:
    run: kubia
spec:
  replicas: 1
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
      - name: kubia-container
        image: rimmon1971/kubia:latest
        ports:
        - containerPort: 8080
          protocol: TCP
      
