apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  namespace: default
  labels:
    run: kubia
spec:
  replicas: 1
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
      - name: kubia
        image: registry.fsimonetti.info/rimmon1971/kubia:0.1
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: sak
        image: registry.fsimonetti.info/leodotcloud/swiss-army-knife

      
